Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/BooksController.cs
using Grpc.Core;
using Grpc.Net.Client;
using Microsoft.AspNetCore.Mvc;
using MyProto;
using System.Linq;
using System.Collections.Generic;
using static MyProto.GrpcBook;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Http.Features;

namespace Client.Controllers
{
    public class BooksController : Controller
    {
        // GET: CustomersController
        public IActionResult Index()
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);
            MyProto.BookList data = client.GetAll(new MyProto.Empty());
            ViewBag.Data = data;

            MyProto.AuthorList AuthorData = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = AuthorData;

            return View();
        }

        // GET: CustomersController/GetCustomer/5
        public IActionResult GetBookById(int id)
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);
            MyProto.Book data = client.GetBookById(new MyProto.IDRequest() { Id = id });
            ViewBag.Data = data;
            MyProto.AuthorList audata = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = audata;

            return View();
        }

        // GET: CustomersController
        public IActionResult GetAllAuthor()
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);
            MyProto.AuthorList data = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = data;

            return View();
        }

        // GET: BooksController/Create
        public IActionResult Create()
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);
            MyProto.AuthorList data = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = data;

            return View();
        }

        // POST: BooksController/Create
        [HttpPost]
        public IActionResult Create(MyProto.CreateBookRequest model)
        {
            if (ModelState.IsValid)
            {
                using var channel = GrpcChannel.ForAddress("https://localhost:5001");
                var client = new GrpcBookClient(channel);

                
                // Create a new book using gRPC
                var response = client.CreateBook(model);
               
                // Redirect to the details page of the newly created book
                return RedirectToAction("Index", new { id = response.Id });
            }

            // If the ModelState is not valid, return to the Create view with errors
            return View(model);
        }

        // GET: BooksController/Update/5
        public IActionResult Update(int id)
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);

            MyProto.AuthorList audata = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = audata;
            // Get the book by ID
            MyProto.Book data = client.GetBookById(new MyProto.IDRequest() { Id = id });

            // Display the book details in the Update view
            return View(data);
        }

        [HttpPost]
        public IActionResult Update(MyProto.Book model)
        {
            if (ModelState.IsValid)
            {
                using var channel = GrpcChannel.ForAddress("https://localhost:5001");
                var client = new GrpcBookClient(channel);

                // Create an UpdateBookRequest object and populate it with data from the Book model
                var updateRequest = new MyProto.UpdateBookRequest
                {
                    Id = model.Id,
                    Name = model.Name,
                    Version = model.Version,
                    Page = model.Page,
                    Price = model.Price,
                    Year = model.Year,
                    AuthorId = model.AuthorId
                };

                // Update the book using gRPC
                var response = client.UpdateBook(updateRequest);

                // Redirect to the details page of the updated book
                return RedirectToAction("Index", new { id = response.Id });
            }

            // If the ModelState is not valid, return to the Update view with errors
            return View(model);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);
            MyProto.Book data = client.GetBookById(new MyProto.IDRequest() { Id = (int)id });
            ViewBag.Data = data;
            MyProto.AuthorList audata = client.GetAllAuthor(new MyProto.Empty());
            ViewBag.AuthorData = audata;
            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new GrpcBookClient(channel);

            // Create an IDRequest with the book ID to be deleted
            var idRequest = new MyProto.IDRequest { Id = id };

            try
            {
                // Call the DeleteBook gRPC method to delete the book
                client.DeleteBook(idRequest);

                // Redirect to the book list or another appropriate page
                return RedirectToAction("Index");
            }
            catch (RpcException ex)
            {
                return View("Error");
            }
        }
    }
}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Views/Books/Create.cshtml
@model MyProto.CreateBookRequest
@{
    MyProto.AuthorList data = ViewBag.AuthorData;
}

<h1>Create Book</h1>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Version">Version:</label>
        <input asp-for="Version" class="form-control" />
        <span asp-validation-for="Version" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Page">Page:</label>
        <input asp-for="Page" class="form-control" />
        <span asp-validation-for="Page" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Year">Year:</label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>


    <div class="form-group">
        <label asp-for="AuthorId">Author:</label>
        <select asp-for="AuthorId" class="form-control">
           
            @foreach (var item in data.Author)
            {
                <option value="@item.AuthorId">@item.AuthorName</option>
            }
        </select>
       
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Client/Views/Books/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    MyProto.Book data = ViewBag.Data;
    MyProto.AuthorList AuthorData = ViewBag.AuthorData;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Id
        </dt>
        <dd class="col-sm-10">
            @data.Id
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @data.Name
        </dd>
        <dt class="col-sm-2">
            Version
        </dt>
        <dd class="col-sm-10">
            @data.Version
        </dd>
        <dt class="col-sm-2">
            Pages
        </dt>
        <dd class="col-sm-10">
            @data.Page
        </dd>
        <dt class="col-sm-2">
            Year
        </dt>
        <dd class="col-sm-10">
            @data.Year
        </dd>
        <dt class="col-sm-2">
            Author
        </dt>
        <dd class="col-sm-10">

            @{
                var author = AuthorData.Author.FirstOrDefault(a => a.AuthorId == data.AuthorId);
                string authorName = (author != null) ? author.AuthorName : "Not Found";
            }
            <p>Author: @authorName</p>

        </dd>
       
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="@data.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
 

Client/Views/Books/GetAllAuthor.cshtml
@{
    ViewData["Title"] = "Index";
    MyProto.AuthorList data = ViewBag.AuthorData;
}


<table class="table" id="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
               Name
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in data.Author)
        {
                <tr>
                    <td>
                        <div>@item.AuthorId</div>
                    </td>
                    <td>
                        <div>@item.AuthorName</div>
                    </td>
                    
                </tr>
        }
    </tbody>
</table>

Client/Views/Books/GetBookById.cshtml
@{
    ViewData["Title"] = "GetCustomer";
    MyProto.Book data = ViewBag.Data;
    MyProto.AuthorList AuthorData = ViewBag.AuthorData;
}


<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Id
        </dt>
        <dd class = "col-sm-10">
           @data.Id
        </dd>
        <dt class = "col-sm-2">
           Name
        </dt>
        <dd class = "col-sm-10">
           @data.Name
        </dd>
        <dt class = "col-sm-2">
            Version
        </dt>
        <dd class = "col-sm-10">
            @data.Version
        </dd>
        <dt class = "col-sm-2">
            Pages
        </dt>
        <dd class = "col-sm-10">
            @data.Page
        </dd>
        <dt class = "col-sm-2">
           Year
        </dt>
        <dd class = "col-sm-10">
          @data.Year
        </dd>
        <dt class="col-sm-2">
            Author
        </dt>
        <dd class="col-sm-10">

            @{
                    var author = AuthorData.Author.FirstOrDefault(a => a.AuthorId == data.AuthorId);
                    string authorName = (author != null) ? author.AuthorName : "Not Found";
                }
                    <p>Author: @authorName</p>
             
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@data.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Client/Views/Books/Index.cshtml
@{
    ViewData["Title"] = "Index";
    MyProto.BookList data = ViewBag.Data;
    MyProto.AuthorList AuthorData = ViewBag.AuthorData;
}
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<table class="table" id="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Version
            </th>
            <th>
                Page
            </th>
            <th>
                Price
            </th>
            <th>
                Year
            </th>
            <th>
                Author
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in data.Book)
        {
            <tr>
                <td>
                    <div>@item.Id</div>
                </td>
                <td>
                    <div>@item.Name</div>
                </td>
                <td>
                    <div>@item.Version</div>
                </td>
                <td>
                    <div>@item.Page</div>
                </td>
                <td>
                    <div>@item.Price</div>
                </td>
                <td>
                    <div>@item.Year</div>
                </td>

                <td>
                    @{
                        var author = AuthorData.Author.FirstOrDefault(a => a.AuthorId == item.AuthorId);
                        string authorName = (author != null) ? author.AuthorName : "Not Found";
                    }
                    <p>Author: @authorName</p>
                </td>

                <td>
                    <a asp-action="Update" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="GetBookById" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Client/Views/Books/Update.cshtml
@model MyProto.Book
@{
    MyProto.AuthorList data = ViewBag.AuthorData;
}
<h1>Edit Book</h1>

<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Version">Version:</label>
        <input asp-for="Version" class="form-control" />
        <span asp-validation-for="Version" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Page">Page:</label>
        <input asp-for="Page" class="form-control" />
        <span asp-validation-for="Page" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Year">Year:</label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="AuthorId">Author:</label>
        <select asp-for="AuthorId" class="form-control">

            @foreach (var item in data.Author)
            {
                    <option value="@item.AuthorId">@item.AuthorName</option>
            }
        </select>

    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0-alpha3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books Manage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

     <script defer src="https://code.jquery.com/jquery-3.5.1.js"></script>
   <script defer src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script defer src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>